version: "3.8"

# Zentraler Environment-Anker
x-env: &risingwave-env
  RUST_LOG: warn,risingwave_meta::hummock::manager::compaction::compaction_group_schedule=error,pgwire::pg_server=warn,rdkafka=error
  ENABLE_TELEMETRY: "false"
  AWS_REGION: us-east-1
  AWS_ENDPOINT_URL: http://192.168.178.79:8100
  S3_ENDPOINT: 192.168.178.79:8100
  S3_BUCKET: risingwave-dev
  S3_PATH: hummok_001_dev


services:
  # --- META NODE ---
  meta-node: # Note: Risingwave is able to start multiple computing nodes even dedicated to streaming or serving (sql)
    image:  risingwavelabs/risingwave:latest
    networks:
      - risingwave_default
    stop_grace_period: 120s
    secrets:
      - ops_s3_storage_pw
      - ops_s3_storage_user

    environment:
      <<: *risingwave-env
      RW_NODE_TYPE: "meta-node"
      RW_NODE_OPTS: >
        --backend sql 
        --sql-endpoint postgres://postgres:@postgres-dev:5432/metadata 
        --listen-addr 0.0.0.0:5690 
        --advertise-addr meta-node:5690 
        --dashboard-host 0.0.0.0:5691 
        --prometheus-listener-addr 0.0.0.0:1250
    configs:
      - source: risingwave_entrypoint_v1
        target: /entrypoint.sh
        mode: 0555
    entrypoint: ["sh", "/entrypoint.sh"]

    ports:
      - "5691:5691"

    healthcheck:
      test: ["CMD", "curl", "-f", "-s", "http://localhost:1250/metrics", "-o", "/dev/null"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 130s

  # --- COMPUTE NODE ---
  compute-node: # Note: Risingwave is able to start multiple computing nodes even dedicated to streaming or serving (sql)
    image:  risingwavelabs/risingwave:latest
    stop_grace_period: 120s
    secrets:
      - ops_s3_storage_pw
      - ops_s3_storage_user
    networks:
      - risingwave_default

    environment:
      <<: *risingwave-env
      RW_NODE_TYPE: "compute-node"
      RW_NODE_OPTS: >
        --listen-addr 0.0.0.0:5688 
        --meta-address http://meta-node:5690  
        --prometheus-listener-addr 0.0.0.0:1250
    configs:
      - source: risingwave_entrypoint_v1
        target: /entrypoint.sh
        mode: 0555
    entrypoint: ["sh", "/entrypoint.sh"]
    healthcheck:
      test: ["CMD", "curl", "-f", "-s", "http://localhost:1250/metrics", "-o", "/dev/null"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 130s

  # --- COMPACTOR NODE ---
  compactor-node: # Note: Risingwave is able to start multiple computing nodes even dedicated to streaming or serving (sql)
    image:  risingwavelabs/risingwave:latest
    stop_grace_period: 120s
    secrets:
      - ops_s3_storage_pw
      - ops_s3_storage_user
    networks:
      - risingwave_default

    environment:
      <<: *risingwave-env
      RW_NODE_TYPE: "compactor-node"
      RW_NODE_OPTS: >
        --listen-addr 0.0.0.0:6660 
        --advertise-addr compactor-node:6660 
        --meta-address http://meta-node:5690  
        --prometheus-listener-addr 0.0.0.0:1250
    configs:
      - source: risingwave_entrypoint_v1
        target: /entrypoint.sh
        mode: 0555
    # WICHTIG: Das hier muss dazu, um das Standard-Verhalten des Images zu ändern
    entrypoint: ["sh", "/entrypoint.sh"]
    healthcheck:
      test: ["CMD", "curl", "-f", "-s", "http://localhost:1250/metrics", "-o", "/dev/null"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 130s

  # --- frontend NODE ---
  frontend-node: # Note: Risingwave is able to start multiple computing nodes even dedicated to streaming or serving (sql)
    image:  risingwavelabs/risingwave:latest
    stop_grace_period: 120s
    secrets:
      - ops_s3_storage_pw
      - ops_s3_storage_user
      - risingwave_tls_key
      - risingwave_tls_cert
    networks:
      - risingwave_default
    environment:
      <<: *risingwave-env
      RW_SSL_CERT: /run/secrets/risingwave_tls_cert
      RW_SSL_KEY: /run/secrets/risingwave_tls_key
      RW_SSL_ENFORCE: "true"
      RW_NODE_TYPE: "frontend-node"
      RW_NODE_OPTS: >
        --listen-addr 0.0.0.0:4566 
        --health-check-listener-addr 0.0.0.0:6786
        --prometheus-listener-addr 0.0.0.0:1250 
        --advertise-addr 0.0.0.0:4566 
        --meta-addr http://meta-node:5690

    configs:
      - source: risingwave_entrypoint_v1
        target: /entrypoint.sh
        mode: 0555
    # WICHTIG: Das hier muss dazu, um das Standard-Verhalten des Images zu ändern
    entrypoint: ["sh", "/entrypoint.sh"]
    ports:
      - "4566:4566"
  risingwave-console:
    image: risingwavelabs/risingwave-console:latest-pgbundle
    networks:
      - risingwave_default
    environment:
      # Passwort für den Login in die Web-UI
      - RCONSOLE_ROOT_PASSWORD=test1234
      # Verbindung zum RisingWave Meta-Node (gRPC)
      - RW_META_ADDR=http://meta-node:5690
      # Verbindung zum RisingWave Frontend (Postgres-Protokoll)
      - RW_FRONTEND_ADDR=frontend-node:4566
      - RW_FRONTEND_USER=root
    volumes:
      - console-data:/var/lib/postgresql
    ports:
      - "8020:8020"
    deploy:
      restart_policy:
        condition: on-failure

  postgres-dev:
    image: "postgres:18"
    stop_grace_period: 120s
    networks:
      - risingwave_default
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=postgres
      - POSTGRES_DB=metadata
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    volumes:
      - "postgres-data:/var/lib/postgresql"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d metadata -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

networks:
  risingwave_default:
    driver: overlay
    attachable: true

volumes:
  postgres-data:
  console-data: # Neues Volume für die interne DB der Console

secrets:
  ops_s3_storage_pw:
    external: true
  ops_s3_storage_user:
    external: true
  risingwave_tls_cert:
    external: true
  risingwave_tls_key:
    external: true

configs:

  risingwave_entrypoint_v1:
    external: true
