version: "3.7"

# Zentraler Environment-Anker
x-env: &risingwave-env
  RUST_LOG: warn,risingwave_meta::hummock::manager::compaction::compaction_group_schedule=error,pgwire::pg_server=warn,rdkafka=error
  ENABLE_TELEMETRY: "false"
  AWS_REGION: us-east-1
  AWS_ENDPOINT_URL: http://192.168.178.79:8100
  S3_ENDPOINT: 192.168.178.79:8100
  S3_BUCKET: risingwave-dev
  S3_PATH: hummok_001_dev

services:
  # --- META NODE ---
  meta-node: # Note: Risingwave is able to start multiple computing nodes even dedicated to streaming or serving (sql)
    image:  risingwavelabs/risingwave:latest
    stop_grace_period: 120s
    secrets:
      - ops_s3_storage_pw
      - ops_s3_storage_user

    environment:
      <<: *risingwave-env
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        # Auslesen der Secrets in temporäre Variablen
        AWS_ACCESS_KEY_ID=`cat /run/secrets/ops_s3_storage_user`
        AWS_SECRET_ACCESS_KEY=`cat /run/secrets/ops_s3_storage_pw`

        # Erstellen der TOML-Datei mit den Inhalten der Secrets
        printf '[system]\nstate_store = "hummock+minio://%s:%s@%s/%s"\n' \
        "$$AWS_ACCESS_KEY_ID" "$$AWS_SECRET_ACCESS_KEY" "$$S3_ENDPOINT" "$$S3_BUCKET" > /tmp/risingwave.toml &&
        printf 'data_directory = "%s"\n' "$$S3_PATH" >> /tmp/risingwave.toml &&

        printf '[storage.s3]\nendpoint = "%s"\naccess_key = "%s"\nsecret_key = "%s"\n' \
        "$$AWS_ENDPOINT_URL" "$$AWS_ACCESS_KEY_ID" "$$AWS_SECRET_ACCESS_KEY" >> /tmp/risingwave.toml &&


        # start meta-node 
        exec /risingwave/bin/risingwave meta-node \
          --config-path /tmp/risingwave.toml \
          --backend sql --sql-endpoint postgres://postgres:@postgres-dev:5432/metadata \
          --listen-addr 0.0.0.0:5690 \
          --advertise-addr meta-node:5690 \
          --dashboard-host 0.0.0.0:5691
    

    ports:
      - "5691:5691"

  # --- COMPUTE NODE ---
  compute-node: # Note: Risingwave is able to start multiple computing nodes even dedicated to streaming or serving (sql)
    image:  risingwavelabs/risingwave:latest
    stop_grace_period: 120s
    secrets:
      - ops_s3_storage_pw
      - ops_s3_storage_user

    environment:
      <<: *risingwave-env
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        # Auslesen der Secrets in temporäre Variablen
        AWS_ACCESS_KEY_ID=`cat /run/secrets/ops_s3_storage_user`
        AWS_SECRET_ACCESS_KEY=`cat /run/secrets/ops_s3_storage_pw`

        # Erstellen der TOML-Datei mit den Inhalten der Secrets
        printf '[system]\nstate_store = "hummock+minio://%s:%s@%s/%s"\n' \
        "$$AWS_ACCESS_KEY_ID" "$$AWS_SECRET_ACCESS_KEY" "$$S3_ENDPOINT" "$$S3_BUCKET" > /tmp/risingwave.toml &&
        printf 'data_directory = "%s"\n' "$$S3_PATH" >> /tmp/risingwave.toml &&

        printf '[storage.s3]\nendpoint = "%s"\naccess_key = "%s"\nsecret_key = "%s"\n' \
        "$$AWS_ENDPOINT_URL" "$$AWS_ACCESS_KEY_ID" "$$AWS_SECRET_ACCESS_KEY" >> /tmp/risingwave.toml &&


        # start compute-node 
        exec /risingwave/bin/risingwave compute-node \
          --config-path /tmp/risingwave.toml \
          --listen-addr 0.0.0.0:5688 \
          --advertise-addr compute-node:5688 \
          --meta-address http://meta-node:5690


  # --- COMPACTOR NODE ---
  compactor-node: # Note: Risingwave is able to start multiple computing nodes even dedicated to streaming or serving (sql)
    image:  risingwavelabs/risingwave:latest
    stop_grace_period: 120s
    secrets:
      - ops_s3_storage_pw
      - ops_s3_storage_user

    environment:
      <<: *risingwave-env
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        # Auslesen der Secrets in temporäre Variablen
        AWS_ACCESS_KEY_ID=`cat /run/secrets/ops_s3_storage_user`
        AWS_SECRET_ACCESS_KEY=`cat /run/secrets/ops_s3_storage_pw`

        # Erstellen der TOML-Datei mit den Inhalten der Secrets
        printf '[system]\nstate_store = "hummock+minio://%s:%s@%s/%s"\n' \
        "$$AWS_ACCESS_KEY_ID" "$$AWS_SECRET_ACCESS_KEY" "$$S3_ENDPOINT" "$$S3_BUCKET" > /tmp/risingwave.toml &&
        printf 'data_directory = "%s"\n' "$$S3_PATH" >> /tmp/risingwave.toml &&

        printf '[storage.s3]\nendpoint = "%s"\naccess_key = "%s"\nsecret_key = "%s"\n' \
        "$$AWS_ENDPOINT_URL" "$$AWS_ACCESS_KEY_ID" "$$AWS_SECRET_ACCESS_KEY" >> /tmp/risingwave.toml &&


        # start compactor-node
        exec /risingwave/bin/risingwave compactor-node \
          --config-path /tmp/risingwave.toml \
          --listen-addr 0.0.0.0:6660 \
          --advertise-addr compactor-node:6660 \
          --meta-address http://meta-node:5690

  # --- frontend NODE ---
  frontend-node: # Note: Risingwave is able to start multiple computing nodes even dedicated to streaming or serving (sql)
    image:  risingwavelabs/risingwave:latest
    stop_grace_period: 120s
    secrets:
      - ops_s3_storage_pw
      - ops_s3_storage_user

    entrypoint: ["/bin/sh", "-c"]
    command: >
      /risingwave/bin/risingwave frontend-node
      --listen-addr 0.0.0.0:4566
      --advertise-addr frontend-node:4566
      --meta-addr http://meta-node:5690
    ports:
      - "4566:4566"

  postgres-dev:
    image: "postgres:18"
    stop_grace_period: 120s
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=postgres
      - POSTGRES_DB=metadata
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    volumes:
      - "postgres-data:/var/lib/postgresql"



volumes:
  postgres-data:


secrets:
  ops_s3_storage_pw:
    external: true
  ops_s3_storage_user:
    external: true

