name: Build Superset Docker Image

on:
  push:
    branches: [ "main" ]  # Passe den Branch an
  workflow_dispatch:      # Manuelles Triggern

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write   # notwendig um in ghcr.io zu pushen
      id-token: write   # falls später OIDC genutzt wird

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/digispine/superset
          echo $PWD
          ls
          docker build -t $IMAGE_NAME:latest -t $IMAGE_NAME:$(date +%s) DataProduct/superset/

      - name: Push Docker image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/digispine/superset
          docker push --all-tags $IMAGE_NAME
