name: Build Superset Docker Image

on:
  push:
    branches: [ "main" ]  # Passe den Branch an
  workflow_dispatch:      # Manuelles Triggern

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write   # notwendig um in ghcr.io zu pushen
      id-token: write   # falls später OIDC genutzt wird

    steps:
      - name: Set up Docker
        uses: docker/setup-docker-action@v4
        with:
          daemon-config: |
            {
              "debug": true,
              "features": {
                "containerd-snapshotter": true
              }
            }
  
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract base image version
        id: version
        run: |
          BASE=$(grep '^FROM' DataProduct/superset/Dockerfile | head -n1 | cut -d':' -f2)
          echo "base_version=$BASE" >> $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Build and push
        uses: docker/build-push-action@v6
          
        with:
          context: DataProduct/superset/
          platforms: linux/amd64,linux/arm64
          load: true
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ steps.version.outputs.base_version }}
            ghcr.io/${{ github.repository }}:latest
